<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="AnomalyEngine"><HintPath>C:\Users\w_x\Desktop\AXOLOTL\src\AnomalyEngine\bin\Debug\net8.0-windows\AnomalyEngine.dll</HintPath></Reference>
  </ItemGroup>
</Project>
